In [2]:
import numpy as np

In [10]:
x = np.ones(10)
np.split(x, 5)

[array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.]),
 array([1., 1.])]

In [37]:
y = np.arange(16.0).reshape(4, 4)
print(y)
np.hsplit(y, [2,3])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.],
        [ 6.],
        [10.],
        [14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]])]

In [ ]:
z = np.arange(64).reshape(4,4,4)
# print(z)
out = np.split(z, 2, axis=1)
print(out)
np.shape(out)

[array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]]]), array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]]])]


(2, 4, 2, 4)

In [81]:
n_heads = 8
z = np.arange(16*32*64).reshape(16, 32, 64)
z
out = np.split(z, n_heads, axis=2)
print("Split shapes:", [x.shape for x in out])
np.shape(out)
stacked_out = np.stack(out, axis=2)
np.shape(stacked_out)

Split shapes: [(16, 32, 8), (16, 32, 8), (16, 32, 8), (16, 32, 8), (16, 32, 8), (16, 32, 8), (16, 32, 8), (16, 32, 8)]


(16, 32, 8, 8)